name = "curroute-push"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["* * * * *"]

[[kv_namespaces]]
binding = "SUBSCRIPTIONS"
id = "6e84e8ae3a024299a4629eef7ba384c9"
